### ISSUE TITLE
API does not support anymore

### ISSUE THREAD

**Issue by naiborhujosua** [amorriscode/book-box#6]
As of December 8th, 2020, Goodreads no longer issues new developer keys for our public developer API and plans to retire the current version of these tools

**Comment by ahmedsaheed** [comment]
Very disheartening

**Comment by ahmedsaheed** [comment]
> As of December 8th, 2020, Goodreads no longer issues new developer keys for our public developer API and plans to retire the current version of these tools

Since this doesn't work anymore, i decided to hack this up. [Library-Box](https://github.com/ahmedsaheed/Library-box). Does absolutely same as book-box, but uses Google Books API
